### ISSUE TITLE
Cannot filter NamedEntity download by contentType

### ISSUE THREAD

**Issue by kylemcdonald** [ICIJ/datashare-tarentula#12]
`tarentula download --type NamedEntity --query 'contentType:"application/pdf"'` returns 0 documents.

`tarentula export-by-query --type NamedEntity` returns 72255 documents.

`tarentula download` returns 3243 documents.

`tarentula export-by-query --query 'contentType:"application/pdf"'` returns 3160 documents.

`find ~/Datashare -type f | wc -l` returns 3410.

I'm having trouble interpreting this. Here's what makes sense to me:

- I have 3410 files.
- 3243 of these documents are indexed.
- 3160 of these documents are PDF files.

What doesn't make sense: where is the 72255 coming from? And why is querying by `'contentType:"application/pdf"'` returning 0 documents for `download` while it works for `export-by-query`?

Thanks!

**Comment by pirhoo** [comment]
Hi Kyle! 

It looks like this is due to the `--type NamedEntity` option you used in your download command.

The `download` command is primarily built to download raw files from Datashare API.

The `export-by-export` uses a slightly different approach to export only metadata to a CSV file.

With both command, the default `--type` value is "Document".

While it makes sense to export metadata from Named Entities (they are ElasticSearch doc like any other), there cannot be "downloaded" since they are not represented as physical files on disk.

To summarize:

* `tarentula export-by-query` export all metadata for all files to a CSV (excluding Named Entities)
* `tarentula export-by-query --query 'contentType:"application/pdf"'` export metadata only for PDF files to a CSV
* `tarentula export-by-query --type NamedEntity` export metadata only for Named Entities to a CSV
* `tarentula download` will download all raw files
* `tarentula download --query 'contentType:"application/pdf"'` will download PDF fuke files
* `tarentula download --type NamedEntity` will download *nothing* because Named Entities have no files

Let me know if it helps.
